[2023-11-28 18:52:47,281][flwr][WARNING] - 
Setting `min_available_clients` lower than `min_fit_clients` or
`min_evaluate_clients` can cause the server to fail when there are too few clients
connected to the server. `min_available_clients` must be set to a value larger
than or equal to the values of `min_fit_clients` and `min_evaluate_clients`.

[2023-11-28 18:52:47,282][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=1, round_timeout=None)
[2023-11-28 18:52:52,726][flwr][INFO] - Flower VCE: Ray initialized with resources: {'object_store_memory': 3260185804.0, 'GPU': 1.0, 'accelerator_type:G': 1.0, 'CPU': 8.0, 'memory': 6520371611.0, 'node:192.168.100.36': 1.0}
[2023-11-28 18:52:52,727][flwr][INFO] - Initializing global parameters
[2023-11-28 18:52:52,727][flwr][INFO] - Requesting initial parameters from one random client
[2023-11-28 18:52:54,074][flwr][INFO] - Received initial parameters from one random client
[2023-11-28 18:52:54,074][flwr][INFO] - Evaluating initial parameters
[2023-11-28 18:52:55,858][flwr][INFO] - initial parameters (loss, other metrics): 181.95416116714478, {'accuracy': 0.1009}
[2023-11-28 18:52:55,859][flwr][INFO] - FL starting
[2023-11-28 18:52:55,859][flwr][DEBUG] - fit_round 1: strategy sampled 10 clients (out of 10)
[2023-11-28 18:52:56,357][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20354, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:56,666][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20354, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:56,795][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20354, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:56,967][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20354, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:57,144][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20354, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:57,314][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20354, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:57,489][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20354, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:59,003][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20356, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:59,404][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20355, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:59,412][flwr][ERROR] - [36mray::launch_and_fit()[39m (pid=20353, ip=192.168.100.36)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 148, in launch_and_fit
    return maybe_call_fit(
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/client.py", line 184, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/flwr/client/app.py", line 297, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 119, in wrapper_measure
    sensor.begin()
  File "/home/tulionpl/miniconda3/envs/FederatedLearning/lib/python3.8/site-packages/pyRAPL/measurement.py", line 59, in begin
    self._energy_begin = self._sensor.energy()
AttributeError: 'NoneType' object has no attribute 'energy'
[2023-11-28 18:52:59,413][flwr][DEBUG] - fit_round 1 received 0 results and 10 failures
[2023-11-28 18:53:01,262][flwr][INFO] - fit progress: (1, 181.95416116714478, {'accuracy': 0.1009}, 5.403580331999365)
[2023-11-28 18:53:01,263][flwr][INFO] - evaluate_round 1: no clients selected, cancel
[2023-11-28 18:53:01,263][flwr][INFO] - FL finished in 5.403819938999732
[2023-11-28 18:53:01,263][flwr][INFO] - app_fit: losses_distributed []
[2023-11-28 18:53:01,263][flwr][INFO] - app_fit: metrics_distributed_fit {}
[2023-11-28 18:53:01,263][flwr][INFO] - app_fit: metrics_distributed {}
[2023-11-28 18:53:01,263][flwr][INFO] - app_fit: losses_centralized [(0, 181.95416116714478), (1, 181.95416116714478)]
[2023-11-28 18:53:01,263][flwr][INFO] - app_fit: metrics_centralized {'accuracy': [(0, 0.1009), (1, 0.1009)]}
